### ISSUE TITLE
Unicode problems.

### ISSUE THREAD

**Issue by jomo666** [mamod/JavaScript-Duktape#2]
Would be nice if you could provide an example how to use unicode with JavaScript::Duktape. Here is an example code in compare with the [JE](https://metacpan.org/pod/JE).

```
use 5.018;
use warnings;
use utf8;
binmode STDOUT, ':utf8';

my $evalstr = <<'//JSEND';
        function uc(s) { return s.toUpperCase(); }
        write( uc("abc αβγ ß") ) // ascii: abc,  greek:alpha beta gamma, german:sharp-s
//JSEND

#JE version
#----------------
use JE;
my $je = JE->new();
$je->new_function( write =>
    sub {
        say "JE : résúlt-", @_;
    }
);
$je->eval($evalstr);

# Duktape version
#----------------
use JavaScript::Duktape;
my $jd = JavaScript::Duktape->new();
$jd->set(write =>
    sub {
        my $duk = shift;
        say "DUK: résúlt-", @_;
    }
);
$jd->eval($evalstr);
```

it prints:

```
JE : résúlt-ABC ΑΒΓ SS
DUK: résúlt-ABC ÎÎÎ SS
```

e.g the JE prints what I want. What is the correct way using unicode with JavaScript::Duktape?

**Comment by mamod** [comment]
Thanks for reporting this.
Duktape deal with strings as UTF-8 encoded by default, the problem is that perl doesn't recognize them to be UTF-8 buffers unless we tell it, so it's been represented and printed as byte string.

I'm not sure if forcing utf8 encoding flag on current JavaScript::Duktape string functions is the best thing to do, so I'm going to introduce a new api `get_utf8_string` to get utf8 strings at the moment.

I'll ping you once I do this and let you know

**Comment by mamod** [comment]
@jomo666 I've updated master branch with new utf8 string function can you please test and report back, it's not an official release on cpan yet so you need to download from master branch, I've used your example above as a quick reference for testing, more tests need to be added though :)

**Comment by jomo666** [comment]
IMHO, not it works perfectly. Even the `$jd->set('some',"úňíčóďě");`  works too. You fixing things faster as i could test them. Thank you - closing. :) :)
