### ISSUE TITLE
seg fault when nested errors are thrown

### ISSUE THREAD

**Issue by rodrigolive** [mamod/JavaScript-Duktape#6]
If a Perl function called from another Perl function throws an error, the whole perl process aborts with a segmentation fault:

```
use strict;
use warnings;
use JavaScript::Duktape;

my $js = JavaScript::Duktape->new();

$js->set( inc => sub{
    shift;
    die "oh no!";
});

$js->set( each => sub{
    shift;
    my $arr = shift;
    my $cb = shift;
    for(@$arr) {
        $cb->($_);
    }
});

$js->eval(q{
    var x=0;
    each([11,22], function(i){
        x+=i; x=inc(x);
    });
});
```

**Comment by mamod** [comment]
Thank you for reporting this :+1:  Duktape use setjmp & longjmp for exception handling which mess with perl's stack when throwing an error, same thing happens when throwing an error from perl, this was difficult to deal with and I thought I created every possible test case until you showed me I was wrong :)

Please test from master branch, I'm going to upload to CPAN soon.
